config/routes.rb
Desempenho::Application.routes.draw do
  
  resources :employments
  devise_for :users, :path => 'usuarios', :path_names => {:sign_in => 'logar', :sign_out => 'sair', :sign_up => 'cadastrar'}
  root :to => "home#index"
  

  resources :surveys do
  resources :survey
  end

  resources :employees do
  resources :employee
  end

  resources :competences do
  resources :competence
  end

  resources :employments do
  resources :employment
  end

  resources :departaments do
  resources :departament
  end
  resources :questions do
  resources :question
  end

  resources :answers do
  resources :answer
  end

end

app/models/employment.rb
class Employment < ActiveRecord::Base
  attr_accessible :name, :competence_id
  belongs_to :competence
  has_many :employees
  has_many :surveys
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController

  layout 'admin'
  respond_to :html, :json

  def index
    @employments = Employment.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    respond_with @employments
  end

  def show
    @employment = get_register(params[:id])
    respond_with @employment
  end

  def new
    @employment = Employment.new
    respond_with @employment
  end

  def edit
    @employment = get_register(params[:id])
    respond_with @employment
  end

  def create
    @employment = Employment.new params[:employment]
    if @employment.save
      flash[:notice] = t :employment_created if @employment.save
      respond_with @employment
    end
  end

  def update
    @employment = get_register(params[:id])
    flash[:notice] = t :employment_updated if @employment.update_attributes params[:employment]
    respond_with @employment
  end

  def destroy
    @employment = get_register(params[:id])
    @employment.destroy
    respond_with @employment
  end

  private
  def get_register(id)
    Employment.find(id)
  end

end

app/helpers/employments_helper.rb
module EmploymentsHelper

end

app/views/employments/_form.html.erb
<%= simple_form_for(@employment) do |f| %>
 <% f.association :competence%>

  <div class="module_content">
    <% if @employment.errors.any? %>
      <div id="error_explanation">
        <h4 class='alert_error'><%= pluralize(@employment.errors.count, "error") %> prohibited this category from being saved:</h4>

        <ul>
        <% @employment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <label><b><%= I18n.t :name %></b></label>
      <%= f.text_field :name %>
    </div>
  <div class="field">
      <label><b><%= I18n.t :competence_id %></b></label>
      <%=f.association :competence, :collection => Competence.all(:order => 'name'),:as => :check_boxes%>
      <%#= f.collection_select :competence_id, Competence.all, :id, :name %>
  </div>

  
  <%= link_to arrow_left, employments_path %>
  <%= submit_link(f) %>
  <%= submit_tag(I18n.t(:clear), class: 'btn btn-inverse', type: "reset" ) %>
  <%= link_to(I18n.t(:show), @employment, class: 'btn') if params[:action] == 'edit' %>
<% end %>

app/views/employments/edit.html.erb
<div class="page-header">
  <h2><%= I18n.t :editing_employment %></h2>
</div>
<%= render 'form' %>

app/views/employments/index.html.erb
<div class="page-header">
  <h2><%= I18n.t :listing_employments %> - <%= link_to I18n.t(:new_employment), new_employment_path, class: 'btn btn-success' %></h2>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= t(:name) %></th>
    </tr>
  </thead>
  
  <tbody>
  <% @employments.each do |employment| %>
    <tr>
      <td><%= employment.name %></td>
      <td><%= link_to I18n.t(:show), employment, class: 'btn' %></td>
      <td><%= link_to I18n.t(:edit), edit_employment_path(employment), class: 'btn btn-primary' %></td>
      <td><%= button_to I18n.t(:delete), { action: :destroy, id: employment.id },:confirm => "Are you sure?", method: :delete, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @employments, previous_label: I18n.t(:previous), next_label: I18n.t(:next) %>
<br />

<%= link_to I18n.t(:new_employment), new_employment_path, class: 'btn btn-success' %>

app/views/employments/new.html.erb
<div class="page-header">
  <h2><%= I18n.t :new_employment %></h2>
</div>
<%= render 'form' %>

app/views/employments/show.html.erb
<%= outgoing_menssage %>
<div class="page-header">
	<h2><%= I18n.t :employment%></h2>
</div>

<table class="table table-bordered table-striped">
	<p> <b><%= I18n.t :name %></b> <br>
		<%= @employment.name %>
	</p>
	
	<b><%= I18n.t :competence %></b> <br>
	<%= @employment.competence.name %>

</table>

	<%= link_to arrow_left, employments_path %>
	<%= link_to I18n.t(:edit), edit_employment_path(@employment), class: 'btn btn-primary' %>