config/routes.rb
Desempenho::Application.routes.draw do
  
  resources :employments
  devise_for :users, :path => 'usuarios', :path_names => {:sign_in => 'logar', :sign_out => 'sair', :sign_up => 'cadastrar'}
  root :to => "home#index"
  

  resources :surveys do
  resources :survey
  end

  resources :employees do
  resources :employee
  end

  resources :competences do
  resources :competence
  end

  resources :employments do
  resources :employment
  end

  resources :departaments do
  resources :departament
  end
  resources :questions do
  resources :question
  end

  resources :answers do
  resources :answer
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :name, :score
  belongs_to :question
end

app/models/competence.rb
class Competence < ActiveRecord::Base
  attr_accessible :name, :enabled
  attr_accessible :questions_attributes
  has_many :employments
  has_and_belongs_to_many :questions
  accepts_nested_attributes_for :questions, :reject_if => :all_blank, :allow_destroy => true

  # Competence.named("Surf")
  #scope :named, lambda {|param| where('name LIKE ?', "%#{param}%") }

  # Competence.named("Surf")
  def self.named(param)
  	where('name LIKE ?', "%#{param}%")
  end

  # c = Competence.last; c.last_question.answers
  def last_question
  	questions.last
  end
end

app/models/departament.rb
class Departament < ActiveRecord::Base
  attr_accessible :name
  has_many :employees
  has_many :surveys
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :name, :identify, :departament_id, :employment_id
  belongs_to :departament
  belongs_to :employment
  has_many :surveys
end

app/models/employment.rb
class Employment < ActiveRecord::Base
  attr_accessible :name, :competence_id
  belongs_to :competence
  has_many :employees
  has_many :surveys
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :answers_attributes
  has_many :answers, :dependent => :destroy
  has_and_belongs_to_many :competences
  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :employee_id, :departament_id, :employment_id, :product
  belongs_to :employee
  belongs_to :departament
  belongs_to :employment
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :token_authenticatable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :login, :enabled, :url_image,:email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
validates_presence_of :login
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  layout 'admin'
  respond_to :html, :json

  def index
    @answers = Answer.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    respond_with @answers
  end

  def show
    @answer = get_register(params[:id])
    respond_with @answer
  end

  def new
    @answer = Answer.new
    respond_with @answer
  end

  def edit
    @answer = get_register(params[:id])
    respond_with @answer
  end

  def create
    @answer = Answer.new params[:answer]
    flash[:notice] = t :answer_created if @answer.save
    respond_with @answer
  end

  def update
    @answer = get_register(params[:id])
    flash[:notice] = t :answer_updated if @answer.update_attributes params[:answer]
    respond_with @answer
  end

  def destroy
    @answer = get_register(params[:id])
    @answer.destroy
    respond_with @answer
  end

  private
  def get_register(id)
    Answer.find(id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  layout 'admin'
  respond_to :html, :json

  def index
    @employees = Employee.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    respond_with @employees
  end

  def show
    @employee = get_register(params[:id])
    respond_with @employee
  end

  def new
    @employee = Employee.new
    respond_with @employee
  end

  def edit
    @employee = get_register(params[:id])
    respond_with @employee
  end

  def create
    @employee = Employee.new params[:employee]
    flash[:notice] = t :employee_created if @employee.save
    respond_with @employee
  end

  def update
    @employee = get_register(params[:id])
    flash[:notice] = t :employee_updated if @employee.update_attributes params[:employee]
    respond_with @employee
  end

  def destroy
    @employee = get_register(params[:id])
    @employee.destroy
    respond_with @employee
  end

  private
  def get_register(id)
    Employee.find(id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	 before_filter :authenticate_user!
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  layout 'admin'
  respond_to :html, :json

  def index
    @questions = Question.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    respond_with @questions
  end

  def show
    @question = get_register(params[:id])
    respond_with @question
  end

  def new
   @question = Question.new
   5.times { @question.answers.build }
   respond_with @question
  end

  def edit
    @question = get_register(params[:id])
    respond_with @question
  end

  def create
   @question = Question.new params[:question]
   flash[:notice] = t :question_created if @question.save
   respond_with @question
  end

  def update
    @question = get_register(params[:id])
    flash[:notice] = t :question_updated if @question.update_attributes params[:question]
    respond_with @question
  end

  def destroy
    @question = get_register(params[:id])
    @question.destroy
    respond_with @question
  end

  private
  def get_register(id)
    Question.find(id)
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  layout 'admin'
  respond_to :html, :json

  def index
    @surveys = Survey.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    respond_with @surveys
  end

  def show
    @survey = get_register(params[:id])
    respond_with @survey
  end

  def new
    @survey = Survey.new
    respond_with @survey
  end

  def edit
    @survey = get_register(params[:id])
    respond_with @survey
  end

  def create
    @survey = Survey.new params[:survey]
    flash[:notice] = t :survey_created if @survey.save
    respond_with @survey
  end

  def update
    @survey = get_register(params[:id])
    flash[:notice] = t :survey_updated if @survey.update_attributes params[:survey]
    respond_with @survey
  end

  def destroy
    @survey = get_register(params[:id])
    @survey.destroy
    respond_with @survey
  end
  def teste
    begin
      @employee = Employee.find(params[:id])
      @employment = @employee.employment
      @competence = @employment.competences
      @competences = @employment.competences 
      rescue
      redirect_to employee_path
    end
   end


  private
  def get_register(id)
    Survey.find(id)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
  def outgoing_menssage
    if notice
      raw "<h4 class='alert_success'>#{notice}</h4>"
    end
  end

  def arrow_left
    image_tag('icons/116767-matte-blue-and-white-square-icon-arrows-arrow-thick-left.png', height: '50px', width: '50px')
  end

  def arrow_right
    image_tag('icons/116768-matte-blue-and-white-square-icon-arrows-arrow-thick-right.png', height: '50px', width: '50px')
  end

  def submit_link(form)
    if params[:action] == 'new'
      form.submit(I18n.t(:create), class: 'btn btn-success')
    else
      form.submit(I18n.t(:update), class: 'btn btn-primary')
    end
  end


end

app/helpers/competences_helper.rb
module CompetencesHelper

end

app/helpers/departaments_helper.rb
module DepartamentsHelper

end

app/helpers/employees_helper.rb
module EmployeesHelper

end

app/helpers/employments_helper.rb
module EmploymentsHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

end

app/helpers/surveys_helper.rb
module SurveysHelper

end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <div class="module_content">
    <% if @answer.errors.any? %>
      <div id="error_explanation">
        <h4 class='alert_error'><%= pluralize(@answer.errors.count, "error") %> prohibited this category from being saved:</h4>

        <ul>
        <% @answer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <label><b><%= I18n.t :name %></b></label>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <label><b><%= I18n.t :score %></b></label>
      <%= f.number_field :score %>
    </div>
  </div>
  <%= link_to arrow_left, answers_path %>
  <%= submit_link(f) %>
  <%= submit_tag(I18n.t(:clear), class: 'btn btn-inverse', type: "reset" ) %>
  <%= link_to(I18n.t(:show), @answer, class: 'btn') if params[:action] == 'edit' %>
<% end %>

app/views/answers/edit.html.erb
<div class="page-header">
  <h2><%= I18n.t :editing_answer %></h2>
</div>
<%= render 'form' %>

app/views/answers/index.html.erb
<div class="page-header">
  <h2><%= I18n.t :listing_answers %> - <%= link_to I18n.t(:new_answer), new_answer_path, class: 'btn btn-success' %></h2>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= t :name %></th>
      <th><%= t :score %></th>
    </tr>
  </thead>
  <tbody>
  <% @answers.each do |answer| %>
    <tr>
      <td><%= answer.name %></td>
      <td><%= answer.score %></td>
      <td><%= link_to I18n.t(:show), answer, class: 'btn' %></td>
      <td><%= link_to I18n.t(:edit), edit_answer_path(answer), class: 'btn btn-primary' %></td>
      <td><%= button_to I18n.t(:delete), { action: :destroy, id: answer.id }, :confirm => "Are you sure?", method: :delete, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @answers, previous_label: I18n.t(:previous), next_label: I18n.t(:next) %>
<br />

<%= link_to I18n.t(:new_answer), new_answer_path, class: 'btn btn-success' %>

app/views/answers/new.html.erb
<div class="page-header">
  <h2><%= I18n.t :new_answer %></h2>
</div>
<%= render 'form' %>

app/views/answers/show.html.erb
<%= outgoing_menssage %>
<div class="page-header">
  <h2><%= I18n.t :answer %></h2>
</div>
<table class="table table-bordered table-striped">
  
  <p><b><%= I18n.t :name %></b><br>
    <%= @answer.name %></p>
  
  <b><%= I18n.t :score %></b><br>
    <%= @answer.score %>
</table>

<%= link_to arrow_left, answers_path %>
<%= link_to I18n.t(:edit), edit_answer_path(@answer), class: 'btn btn-primary' %>

app/views/employees/_form.html.erb
<%= simple_form_for(@employee) do |f| %>
<div class="module_content">
  <% if @employee.errors.any? %>
  <div id="error_explanation">
    <h4 class='alert_error'><%= pluralize(@employee.errors.count, "error") %> prohibited this category from being saved:</h4>

    <ul>
      <% @employee.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <label><b><%= I18n.t :name %></b></label>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <label><b><%= I18n.t :identify %></b></label>
    <%= f.number_field :identify %>
  </div>
  <div class="field">
    <label><b><%= I18n.t :departament_id %></b></label>
    <%= f.collection_select :departament_id, Departament.all, :id, :name %>
  </div>
  <div class="field">
    <label><b><%= I18n.t :employment_id %></b></label>
    <%= f.collection_select :employment_id, Employment.all, :id, :name %>
  </div>
</div>
<%= link_to arrow_left, employees_path %>
<%= submit_link(f) %>
<%= submit_tag(I18n.t(:clear), class: 'btn btn-inverse', type: "reset" ) %>
<%= link_to(I18n.t(:show), @employee, class: 'btn') if params[:action] == 'edit' %>
<% end %>

app/views/employees/edit.html.erb
<div class="page-header">
  <h2><%= I18n.t :editing_employee %></h2>
</div>
<%= render 'form' %>

app/views/employees/index.html.erb
<div class="page-header">
  <h2><%= I18n.t :listing_employees %> - <%= link_to I18n.t(:new_employee), new_employee_path, class: 'btn btn-success' %></h2>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= t :name %></th>
      <th><%= t :identify %></th>
      <th><%= t :departament %></th>
      <th><%= t :employment %></th>
    </tr>
  </thead>
  <tbody>
  <% @employees.each do |employee| %>
    <tr>
      <td><%= employee.name %></td>
      <td><%= employee.identify %></td>
      <td><%= employee.departament.name %></td>
      <td><%= employee.employment.name %></td>
      <td><%= link_to I18n.t(:show), employee, class: 'btn' %></td>
      <td><%= link_to I18n.t(:edit), edit_employee_path(employee), class: 'btn btn-primary' %></td>
      <td><%= button_to I18n.t(:delete), { action: :destroy, id: employee.id },:confirm => "Are you sure?", :method => :delete, :class => 'btn btn-danger' %> </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @employees, previous_label: I18n.t(:previous), next_label: I18n.t(:next) %>
<br />

<%= link_to I18n.t(:new_employee), new_employee_path, class: 'btn btn-success' %>

app/views/employees/new.html.erb
<div class="page-header">
  <h2><%= I18n.t :new_employee %></h2>
</div>
<%= render 'form' %>

app/views/employees/show.html.erb
<%= outgoing_menssage %>
<div class="page-header">
	<h2><%= I18n.t :employee %></h2>
</div>

<table class="table table-bordered table-striped">

	<p> <b><%= I18n.t :name %></b> <br>
		<%= @employee.name %>
	</p>

	<p> <b><%= I18n.t :identify %></b><br>
		<%= @employee.identify %>
	</p>

	<p> <b><%= I18n.t :departament %></b><br>
		<%= @employee.departament.name %>
	</p>

	<p><b><%= I18n.t :employment %></b><br>
		<%= @employee.employment.name %>
	</p>

</table>

<%= link_to arrow_left, employees_path %>
<%= link_to I18n.t(:edit), edit_employee_path(@employee), class: 'btn btn-primary' %>

app/views/questions/_answer_fields.html.erb
<td> <div class="field">
  <label><b><%= I18n.t :answer %></b></label>
  <%= f.text_field :name %>
 </div>
 <div class="field">
  <label><b><%= I18n.t :score %></b></label>
 <%= f.number_field :score %>
</div>
</td>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <div class="module_content">
    <% if @question.errors.any? %>
      <div id="error_explanation">
        <h4 class='alert_error'><%= pluralize(@question.errors.count, "error") %> prohibited this category from being saved:</h4>

        <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <label><b><%= I18n.t :name %></b></label>
      <%= f.text_field :name %>
    </div>

    <%= f.fields_for :answers do |builder| %>
    <%= render 'answer_fields', :f => builder %>
    <% end %>
    
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/questions/edit.html.erb
<div class="page-header">
  <h2><%= I18n.t :editing_question %></h2>
</div>
<%= render 'form' %>

app/views/questions/index.html.erb
<div class="page-header">
  <h2><%= I18n.t :listing_questions %> - <%= link_to I18n.t(:new_question), new_question_path, class: 'btn btn-success' %></h2>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= t :name %></th>

    </tr>
  </thead>
  <tbody>
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.name %></td>

      <td><%= link_to I18n.t(:show), question, class: 'btn' %></td>
      <td><%= link_to I18n.t(:edit), edit_question_path(question), class: 'btn btn-primary' %></td>
      <td><%= button_to I18n.t(:delete), { action: :destroy, id: question.id }, :confirm => "Are you sure?", :method => :delete, :class => 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @questions, previous_label: I18n.t(:previous), next_label: I18n.t(:next) %>
<br />

<%= link_to I18n.t(:new_question), new_question_path, class: 'btn btn-success' %>

app/views/questions/new.html.erb
<div class="page-header">
  <h2><%= I18n.t :new_question %></h2>
</div>
<%= render 'form' %>

app/views/questions/show.html.erb
<%= outgoing_menssage %>
<div class="page-header">
  <h2><%= I18n.t :showing %></h2>
</div>
<table class="table table-bordered table-striped">
  <tr>
    <td><b><%= I18n.t :question %></b></td>
    <td><%= @question.name %></td>
  </tr>
     
    <% for answer in @question.answers %>
      <tr>
      	<td><b><%= I18n.t :answer %></b></td>
     	 <td><%=h answer.name %></td>
      </tr>
    <% end %>
  
</table>

<%= link_to arrow_left, questions_path %>
<%= link_to I18n.t(:edit), edit_question_path(@question), class: 'btn btn-primary' %>

app/views/surveys/_form.html.erb
<%= simple_form_for(@survey) do |f| %>
  <div class="module_content">
    <% if @survey.errors.any? %>
      <div id="error_explanation">
        <h4 class='alert_error'><%= pluralize(@survey.errors.count, "error") %> prohibited this category from being saved:</h4>

        <ul>
        <% @survey.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <label><b><%= I18n.t :employee %></b></label>
      <%= f.collection_select :employee_id, Employee.all, :id, :name %>
    </div>
    <div class="field">
      <label><b><%= I18n.t :departament_id %></b></label>
      <%= f.collection_select :departament_id, Departament.all, :id, :name %>
    </div>
    <div class="field">
      <label><b><%= I18n.t :employment_id %></b></label>
      <%= f.collection_select :employment_id, Employment.all, :id, :name %>
    </div>
    <div class="field">
      <label><b><% I18n.t :product %></b></label>
      <% f.number_field :product %>
    </div>
  </div>
  <%= link_to arrow_left, surveys_path %>
  <%= submit_link(f) %>
  <%= submit_tag(I18n.t(:clear), class: 'btn btn-inverse', type: "reset" ) %>
  <%= link_to(I18n.t(:show), @survey, class: 'btn') if params[:action] == 'edit' %>
<% end %>

app/views/surveys/edit.html.erb
<div class="page-header">
  <h2><%= I18n.t :editing_survey %></h2>
</div>
<%= render 'form' %>

app/views/surveys/index.html.erb
<div class="page-header">
  <h2><%= I18n.t :listing_surveys %> - <%= link_to I18n.t(:new_survey), new_survey_path, class: 'btn btn-success' %></h2>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= t :employee %></th>
      <th><%= t :departament %></th>
      <th><%= t :employment %></th>
      <th><%= t :product %></th>

    </tr>
  </thead>
  <tbody>
  <% @surveys.each do |survey| %>
    <tr>
      <td><%= survey.employee.name %></td>
      <td><%= survey.departament.name %></td>
      <td><%= survey.employment.name %></td>

      <td><%= link_to I18n.t(:show), survey, class: 'btn' %></td>
      <td><%= link_to I18n.t(:edit), edit_survey_path(survey), class: 'btn btn-primary' %></td>
      <td><%= button_to I18n.t(:delete), { action: :destroy, id: survey.id }, method: :delete, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @surveys, previous_label: I18n.t(:previous), next_label: I18n.t(:next) %>
<br />

<%= link_to I18n.t(:new_survey), new_survey_path, class: 'btn btn-success' %>

app/views/surveys/new.html.erb
<div class="page-header">
  <h2><%= I18n.t :new_survey %></h2>
</div>
<%= render 'form' %>

app/views/surveys/show.html.erb
<%= outgoing_menssage %>
<div class="page-header">
  <h2><%= I18n.t :survey %></h2>
</div>

<table class="table table-bordered table-striped">

  <p><b><%= I18n.t :employee %></b><br>
    <%= @survey.employee.name %>
  </p>


  <p><b><%= I18n.t :departament %></b><br>
    <%= @survey.departament.name %>
  </p>


  <p><b><%= I18n.t :employment %></b><br>
    <%= @survey.employment.name %>
  </p>


  <p><b><% I18n.t :product %></b><br>
    <% @survey.product %>
  </p>
</table>

<%= link_to arrow_left, surveys_path %>
<%= link_to I18n.t(:edit), edit_survey_path(@survey), class: 'btn btn-primary' %>