config/routes.rb
Desempenho::Application.routes.draw do
  
  resources :employments
  devise_for :users, :path => 'usuarios', :path_names => {:sign_in => 'logar', :sign_out => 'sair', :sign_up => 'cadastrar'}
  root :to => "home#index"
  

  resources :surveys do
  resources :survey
  end

  resources :employees do
  resources :employee
  end

  resources :competences do
  resources :competence
  end

  resources :employments do
  resources :employment
  end

  resources :departaments do
  resources :departament
  end
  resources :questions do
  resources :question
  end

  resources :answers do
  resources :answer
  end

end

app/models/competence.rb
class Competence < ActiveRecord::Base
  attr_accessible :name, :enabled
  attr_accessible :questions_attributes
  has_many :employments
  has_and_belongs_to_many :questions
  accepts_nested_attributes_for :questions, :reject_if => :all_blank, :allow_destroy => true

  # Competence.named("Surf")
  #scope :named, lambda {|param| where('name LIKE ?', "%#{param}%") }

  # Competence.named("Surf")
  def self.named(param)
  	where('name LIKE ?', "%#{param}%")
  end

  # c = Competence.last; c.last_question.answers
  def last_question
  	questions.last
  end
end

app/controllers/competences_controller.rb
class CompetencesController < ApplicationController

  layout 'admin'
  respond_to :html, :json

  def index
    @competences = Competence.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    respond_with @competences
  end

  def show
    @competence = get_register(params[:id])
    respond_with @competence 
    
  end

  def new
    @competence = Competence.new
    question = @competence.questions.build
    5.times { question.answers.build }
    respond_with @competence
  end

  def edit
    @competence = get_register(params[:id])
    respond_with @competence
  end

  def create
    @competence = Competence.new params[:competence]

    flash[:notice] = t :competence_created if @competence.save
    respond_with @competence
  end

  def update
    @competence = get_register(params[:id])

    flash[:notice] = t :competence_updated if @competence.update_attributes params[:competence]
    respond_with @competence
  end

  def destroy
    @competence = get_register(params[:id])
    @competence.destroy

    respond_with @competence
  end

  private
  def get_register(id)
    Competence.find(id)
  end

end

app/helpers/competences_helper.rb
module CompetencesHelper

end

app/views/competences/_answer_fields.html.erb
<td> <div class="field">
  <label><b><%= I18n.t :answer %></b></label>
  <%= f.text_field :name %>
 </div>
 <div class="field">
  <label><b><%= I18n.t :score %></b></label>
 <%= f.number_field :score %>
</div>
</td>

app/views/competences/_form.html.erb
<%= form_for(@competence) do |f| %>
  <div class="module_content">
    <% if @competence.errors.any? %>
      <div id="error_explanation">
        <h4 class='alert_error'><%= pluralize(@competence.errors.count, "error") %> prohibited this category from being saved:</h4>
        <ul>
        <% @competence.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <label><b><%= I18n.t :name %></b></label>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <label><b><%= I18n.t :enabled %></b></label>
      <%= f.check_box :enabled %>
    </div>
    <div class="field">
      <%= f.fields_for :questions do |builder| %>
      <%= render "question_fields", :f => builder %>
    </div>
  <% end %>
  </div>

  <%= link_to arrow_left, competences_path %>
  <%= submit_link(f) %>
  <%= submit_tag(I18n.t(:clear), class: 'btn btn-inverse', type: "reset" ) %>
  <%= link_to(I18n.t(:show), @competence, class: 'btn') if params[:action] == 'edit' %>
<% end %>

app/views/competences/_question_fields.html.erb
<td> 
<div class="field">
  <label><b><%= I18n.t :question %><br /></label>
  <%= f.text_area :name, :rows => 3 %><br />
</div>
<div class="field">
	<%= f.fields_for :answers do |builder| %>
	  <%= render "answer_fields", :f => builder %>
	<% end %>
</div>
</td>

app/views/competences/edit.html.erb
<div class="page-header">
  <h2><%= I18n.t :editing_competence %></h2>
</div>
<%= render 'form' %>

app/views/competences/index.html.erb
<div class="page-header">
  <h2><%= I18n.t :listing_competences %> - <%= link_to I18n.t(:new_competence), new_competence_path, class: 'btn btn-success' %></h2>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= t :name %></th>
      <th><%= t :enabled %></th>
    </tr>
  </thead>
  <tbody>
  <% @competences.each do |competence| %>
    <tr>
      <td><%= competence.name %></td>
      <td><%= competence.enabled %></td>
      <td><%= link_to I18n.t(:show), competence, class: 'btn' %></td>
      <td><%= link_to I18n.t(:edit), edit_competence_path(competence), class: 'btn btn-primary' %></td>
      <td><%= button_to I18n.t(:delete), { action: :destroy, id: competence.id },:confirm => "Are you sure?", method: :delete, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @competences, previous_label: I18n.t(:previous), next_label: I18n.t(:next) %>
<br />

<%= link_to I18n.t(:new_competence), new_competence_path, class: 'btn btn-success' %>

app/views/competences/new.html.erb
<div class="page-header">
  <h2><%= I18n.t :new_competence %></h2>
</div>
<%= render 'form' %>

app/views/competences/show.html.erb
<%= outgoing_menssage %>
<div class="page-header">
  <h2><%= I18n.t :showing %></h2>
</div>
<table class="table table-bordered table-striped">
  <b><%= I18n.t :name %></b>
  <%= @competence.name %> <br />

    <b><%= I18n.t :enabled %></b> 
    <%= @competence.enabled %><br />
   
<% for question in @competence.questions %>
<b><%= I18n.t :question %></b>
<%=h question.name %> <br />

    <% for answer in question.answers %>
    <b><%= I18n.t :answer %></b>
      <%=h answer.name %>
    <b><%= I18n.t :score %></b>
      <%=h answer.score %> <br />
    <% end %>
   
<% end %>

</table>



<%= link_to arrow_left, competences_path %>
<%= link_to I18n.t(:edit), edit_competence_path(@competence), class: 'btn btn-primary' %>