config/routes.rb
Desempenho::Application.routes.draw do
  
  resources :employments
  devise_for :users, :path => 'usuarios', :path_names => {:sign_in => 'logar', :sign_out => 'sair', :sign_up => 'cadastrar'}
  root :to => "home#index"
  

  resources :surveys do
  resources :survey
  end

  resources :employees do
  resources :employee
  end

  resources :competences do
  resources :competence
  end

  resources :employments do
  resources :employment
  end

  resources :departaments do
  resources :departament
  end
  resources :questions do
  resources :question
  end

  resources :answers do
  resources :answer
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :name, :score
  belongs_to :question
end

app/models/competence.rb
class Competence < ActiveRecord::Base
  attr_accessible :name, :enabled
  attr_accessible :questions_attributes
  has_many :employments
  has_and_belongs_to_many :questions
  accepts_nested_attributes_for :questions, :reject_if => :all_blank, :allow_destroy => true

  # Competence.named("Surf")
  #scope :named, lambda {|param| where('name LIKE ?', "%#{param}%") }

  # Competence.named("Surf")
  def self.named(param)
  	where('name LIKE ?', "%#{param}%")
  end

  # c = Competence.last; c.last_question.answers
  def last_question
  	questions.last
  end
end

app/models/departament.rb
class Departament < ActiveRecord::Base
  attr_accessible :name
  has_many :employees
  has_many :surveys
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :name, :identify, :departament_id, :employment_id
  belongs_to :departament
  belongs_to :employment
  has_many :surveys
end

app/models/employment.rb
class Employment < ActiveRecord::Base
  attr_accessible :name, :competence_id
  belongs_to :competence
  has_many :employees
  has_many :surveys
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :answers_attributes
  has_many :answers, :dependent => :destroy
  has_and_belongs_to_many :competences
  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :employee_id, :departament_id, :employment_id, :product
  belongs_to :employee
  belongs_to :departament
  belongs_to :employment
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :token_authenticatable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :login, :enabled, :url_image,:email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
validates_presence_of :login
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  layout 'admin'
  respond_to :html, :json

  def index
    @answers = Answer.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    respond_with @answers
  end

  def show
    @answer = get_register(params[:id])
    respond_with @answer
  end

  def new
    @answer = Answer.new
    respond_with @answer
  end

  def edit
    @answer = get_register(params[:id])
    respond_with @answer
  end

  def create
    @answer = Answer.new params[:answer]
    flash[:notice] = t :answer_created if @answer.save
    respond_with @answer
  end

  def update
    @answer = get_register(params[:id])
    flash[:notice] = t :answer_updated if @answer.update_attributes params[:answer]
    respond_with @answer
  end

  def destroy
    @answer = get_register(params[:id])
    @answer.destroy
    respond_with @answer
  end

  private
  def get_register(id)
    Answer.find(id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	 before_filter :authenticate_user!
  def index
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  layout 'admin'
  respond_to :html, :json

  def index
    @surveys = Survey.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    respond_with @surveys
  end

  def show
    @survey = get_register(params[:id])
    respond_with @survey
  end

  def new
    @survey = Survey.new
    respond_with @survey
  end

  def edit
    @survey = get_register(params[:id])
    respond_with @survey
  end

  def create
    @survey = Survey.new params[:survey]
    flash[:notice] = t :survey_created if @survey.save
    respond_with @survey
  end

  def update
    @survey = get_register(params[:id])
    flash[:notice] = t :survey_updated if @survey.update_attributes params[:survey]
    respond_with @survey
  end

  def destroy
    @survey = get_register(params[:id])
    @survey.destroy
    respond_with @survey
  end
  def teste
    begin
      @employee = Employee.find(params[:id])
      @employment = @employee.employment
      @competence = @employment.competences
      @competences = @employment.competences 
      rescue
      redirect_to employee_path
    end
   end


  private
  def get_register(id)
    Survey.find(id)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
  def outgoing_menssage
    if notice
      raw "<h4 class='alert_success'>#{notice}</h4>"
    end
  end

  def arrow_left
    image_tag('icons/116767-matte-blue-and-white-square-icon-arrows-arrow-thick-left.png', height: '50px', width: '50px')
  end

  def arrow_right
    image_tag('icons/116768-matte-blue-and-white-square-icon-arrows-arrow-thick-right.png', height: '50px', width: '50px')
  end

  def submit_link(form)
    if params[:action] == 'new'
      form.submit(I18n.t(:create), class: 'btn btn-success')
    else
      form.submit(I18n.t(:update), class: 'btn btn-primary')
    end
  end


end

app/helpers/competences_helper.rb
module CompetencesHelper

end

app/helpers/departaments_helper.rb
module DepartamentsHelper

end

app/helpers/employees_helper.rb
module EmployeesHelper

end

app/helpers/employments_helper.rb
module EmploymentsHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

end

app/helpers/surveys_helper.rb
module SurveysHelper

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Description">
    <meta name="keywords" content="Keywords">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <%= javascript_include_tag "html5.js" %>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "bootstrap.css", "bootstrap-responsive.css", "docs.css" %>
    <%= csrf_meta_tags %>

  </head>

  <body class="preview" data-spy="scroll" data-target=".subnav" data-offset="50">
    <!-- Navbar
      ================================================== -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
         <% unless current_user.nil? %>
            <div class="brand-right"><%= current_user.email %> <%= link_to I18n.t(:logout), destroy_user_session_path, method: :delete, class: 'btn btn-danger' %></div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <!-- Masthead
      ================================================== -->
      <header class="jumbotron subhead" id="overview">
        <div class="subnav">
          <ul class="nav nav-pills">
            <li><%= link_to t(:home), root_path%></li>
            <li><%= link_to t(:employees),employees_path%></li>
            <li><%= link_to t(:departaments),departaments_path%></li>
            <li><%= link_to t(:employments),employments_path%></li>
            <li><%= link_to t(:competences),competences_path%></li>
            <li><%= link_to t(:questions),questions_path%></li>
            <li><%= link_to t(:answers),answers_path%></li>
            <li><%= link_to t(:surveys),surveys_path%></li>
          </ul>
        </div>
      </header>

      <%= yield %>

      <!-- Le javascript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <%= javascript_include_tag "jquery-1.7.2.min.js", "bootstrap.min.js", "app.js", "bootswatch.js" %>

      <!-- Footer
      ================================================== -->
      <footer class="footer">
        <center><p>Footer</p></center>
      </footer>

    </div><!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Desempenho</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>
    <nav>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
      <% unless current_user.nil? %>
      <div class="brand-right"><%= current_user.email %> <%= link_to I18n.t(:logout), destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
      </div>
      </div>
    </div>
    </nav>
    </div>
    <div class="container">
      <% unless current_user.nil? %>
      <div class="brand-right"><%= current_user.email %> <%= link_to I18n.t(:logout), destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
    <br/>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div id="user_nav">
      <%= link_to 'Registrar', new_user_registration_path %> ou <%= link_to 'Logar', new_user_session_path %>
      <% end %>
<%= yield %>
</body>
</html>